# Week 3 Lab 2: Dictionaries and Intro to pandas DataFrames
**Name:** Abraham Kim
**Date:** 2026-08-01

In [3]:
student = {
    "name": "Maya",
    "score": 88,
    "hours_studied": 5,
    "attendance_rate": 0.95
}

print(student)

{'name': 'Maya', 'score': 88, 'hours_studied': 5, 'attendance_rate': 0.95}

Why is a dictionary better than a list for representing this one student record?
A dictionary has more features like taking attributes from a set of data than a list.

In [4]:
print(student["name"])
print(student["score"])
print(student["hours_studied"])

Maya
88
5

What happens if you misspell a key name?
It makes a key error

In [5]:
student["status"] = "Pass"
student["score"] = 90

print(student)

{'name': 'Maya', 'score': 90, 'hours_studied': 5, 'attendance_rate': 0.95, 'status': 'Pass'}

What is the difference between adding a new key and updating an existing key?
Both use the same syntax and if a key doesn't exist Python add it as a new entry.

In [6]:
students = [
    {"name": "Maya", "score": 88, "hours": 5},
    {"name": "Alex", "score": 92, "hours": 7},
    {"name": "Sam", "score": 75, "hours": 3},
    {"name": "Jordan", "score": 64, "hours": 2}
]

print(students)

[{'name': 'Maya', 'score': 88, 'hours': 5}, {'name': 'Alex', 'score': 92, 'hours': 7}, {'name': 'Sam', 'score': 75, 'hours': 3}, {'name': 'Jordan', 'score': 64, 'hours': 2}]

In this structure, what does each dictionary represent?
Each dicitonary is one student's record, which has all the other data, score, hours, etc.

In [7]:
for student in students:
    print(student["name"], student["score"])

Maya 88
Alex 92
Sam 75
Jordan 64

Why is it useful that every record uses the same keys?
Consistent keys let you loop and access the same info every time.

In [8]:
import pandas as pd

df = pd.DataFrame(students)
print(df)

     name  score  hours
0    Maya     88      5
1    Alex     92      7
2     Sam     75      3
3  Jordan     64      2

What changed when the records became a DataFrame?
Pandas made a structured table with rows and columns.

In [9]:
print("Shape:", df.shape)
print("Columns:", list(df.columns))

df.head()

Shape: (4, 3)
Columns: ['name', 'score', 'hours']

     name  score  hours
0    Maya     88      5
1    Alex     92      7
2     Sam     75      3
3  Jordan     64      2

5 rows and 4 columns
Column names: name, score, hours

In [10]:
df.info()

df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   score   4 non-null      int64
 2   hours   4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

           score     hours
count   4.000000  4.000000
mean   79.750000  4.250000
std    12.763881  2.217356
min    64.000000  2.000000
25%    72.250000  2.750000
50%    81.500000  4.000000
75%    89.000000  5.500000
max    92.000000  7.000000

info() shows the data type for each column and it becomes more specific.

In [11]:
print(df["score"])

student_view = df[["name", "score"]]
print(student_view)

average_score = df["score"].mean()
print("Average score:", average_score)

0    88
1    92
2    75
3    64
Name: score, dtype: int64
     name  score
0    Maya     88
1    Alex     92
2     Sam     75
3  Jordan     64
Average score: 79.75

Because inner brackets create a list of column names and passing list to df[...] tells pandas to return a dataframe with many columns.

In [12]:
def label_score(score):
    if score >= 70:
        return "Pass"
    return "Needs Review"

df["status"] = df["score"].apply(label_score)
print(df)

     name  score  hours        status
0    Maya     88      5          Pass
1    Alex     92      7          Pass
2     Sam     75      3          Pass
3  Jordan     64      2  Needs Review

 How does apply() connect a Python function to a pandas column?

apply() runs your function once for each value in the column, passing that value in the argument and passing each value into a new Series

In [13]:

import pandas as pd

products = [
    {"product": "Keyboard", "category": "Accessories", "quantity": 3, "price": 49.99, "rating": 4.5},
    {"product": "Mouse",    "category": "Accessories", "quantity": 5, "price": 19.99, "rating": 4.2},
    {"product": "Monitor",  "category": "Displays",    "quantity": 2, "price": 149.99, "rating": 4.7},
    {"product": "Laptop",   "category": "Computers",   "quantity": 4, "price": 899.99, "rating": 4.8},
    {"product": "Webcam",   "category": "Accessories", "quantity": 6, "price": 39.99, "rating": 3.9}
]

df = pd.DataFrame(products)

print("Shape:", df.shape)
print("Columns:", df.columns.tolist())

print(df.head())

df["total_value"] = df["quantity"] * df["price"]

average_rating = df["rating"].mean()
print("Average rating:", round(average_rating, 2))

Shape: (5, 5)
Columns: ['product', 'category', 'quantity', 'price', 'rating']
    product     category  quantity   price  rating
0  Keyboard  Accessories         3   49.99     4.5
1     Mouse  Accessories         5   19.99     4.2
2   Monitor     Displays         2  149.99     4.7
3    Laptop    Computers         4  899.99     4.8
4    Webcam  Accessories         6   39.99     3.9
Average rating: 4.42

In [14]:
import pandas as pd

products = [
    {"product": "Keyboard", "quantity": 3, "price": 49.99},
    {"product": "Mouse", "quantity": 5, "price": 19.99}
]

df = pd.DataFrame(products)
df["total_value"] = df["quantity"] * df["price"]
print(df["total_value"])

0    149.97
1     99.95
Name: total_value, dtype: float64